apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: service
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app.kubernetes.io/component: service
        app: java-app
    spec:
      containers:
        - name: java-app
          image: yashpareek99/javaapp-image:${BUILD_ID}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
