apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service
  name: java-app
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: java-app
  type: NodePort